version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "02:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "02:00"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      all-actions:
        applies-to: version-updates
        patterns: ["*"]
