name: 'stellar_dbt'
version: '1.0.0'
config-version: 2

profile: 'stellar_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stellar_dbt:
    samples:
      +enabled: "{{ true if target.name=='samples' else false }}"
      +docs:
        show: false
      +materialized: table
    staging:
      +materialized: ephemeral
    marts:
      +materialized: table